name: PR
on: [pull_request]

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn lint
